version: "3"
 
services:   
  servicio_php-apache-xdebug:
    container_name: OsirisSpellingSoftware
    build: .
    volumes:
      - ./OsirisSpellingSoftware:/var/www/html
      - ./xdebug:/var/logs/xdebug
    ports:
      - 8080:80

  db:
   container_name: dbXdebug
   image: mysql
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: osiris
    MYSQL_USER: usuario
    MYSQL_PASSWORD: abc123.
   volumes:
    - ./dbdata:/var/lib/mysql
   ports:
     - 9906:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    
    

